### PR TITLE
Bs dscs 539 fa copy role

### PR DESCRIPTION
**Pull request by bsingh-nla**
10 new copy roles added finding aid 1, finding aid 2 ...finding aid 10

@scoen , @AaronCMuller , @ninhnguyen , @shuangzhou can you please look.

### CODE REVIEW

**Comment by AaronCMuller** [comment]
I have rather strong feelings about this pull request. If possible I'd like to talk about this with Kavinga and Terence.

**Comment by bsingh-nla** [comment]
@terenceingram , @AaronCMuller, @scoen Shaun had strong feelings too, it looks like we need to talk about it!

**Comment by AaronCMuller** [comment]
@shuangzhou Why did you merge this?

**Comment by terenceingram** [comment]
@bsingh-nla Can you revert this until we sort out the best approach?

**Comment by shuangzhou** [comment]
@AaronCMuller I merged the change as the code looked ok, now I see that there's reason of concern for this, happy for it to be reverted.

**Comment by bsingh-nla** [comment]
@terenceingram we are not able to revert it from github. I'll made code change.

**Pull request merged**
