### PR TITLE
Introduced sql so modified objects query is now directly through the database, not amber.

### PR DESCRIPTION
**Pull request by josephcurtis**
http://ourweb.nla.gov.au/apps/jira/browse/DSCS-2163

Modified objects query was being run over basically the whole database, and since amber doesn't have any in-built concept of limiting query results, it was ooming.  Split this specific case out into an SQL query so limiting could be introduced.

Please don't delete this branch after merging.  I will likely do some further optimisations.

@scoen @terenceingram @yetti @JonathanShaw @snezanam @MingtaoSun @sjacob

### CODE REVIEW

**Comment by shuangzhou** [comment]
Looks good to me.

**Comment by sjacob** [comment]
Looks fine to me.

**Comment by scoen** [comment]
Looks good to me too. Could you just bump the version in the pom before i merge ?

**Comment by MingtaoSun** [comment]
:+1:

**Comment by yetti** [comment]
Looks fine :+1:

**Comment by AaronCMuller** [comment]
Good to see this got fixed.

**Pull request merged**
