### PR TITLE
Dscs 125

### PR DESCRIPTION
**Pull request by shuangzhou**
This request includes fix for container extraction and data validation points.

### CODE REVIEW

**Comment by snezanam** [comment]
Just wandering  about 
if (eadEntityEntries.size() == 0) {
String ord = (i == 0)? "1st" : (i == 1)? "2nd" : (i == 2)? "3rd" : "" + i + "th";
throw new EADValidationException("FAILED_EXTRACT_ENTITIES", ord, collectionWork.getObjId());
}

if ord should be  i + 1 in all cases or just  when i is  0-2

**Comment by shuangzhou** [comment]
Yep, well spotted, done.

**Comment by scoen** [comment]
Unsure how many entities are expected, but it will write funny things after the 20th eg: 21th, 22th and 23th etc. Still, i expect this will be rare.

**Comment by shuangzhou** [comment]
Good point, I haven't thought through this very well, will try to come up with a better solution.

**Pull request merged**
