### PR TITLE
Sc fix txn query

### PR DESCRIPTION
**Pull request by scoen**
I fixed these queries as i need them to 'actually' work (rather than just compiling) for the file versioning stuff i'm working on. :) They now have tests too.

### CODE REVIEW

**Comment by scoen** [comment]
@yetti @danielbaker @MingtaoSun @AaronCMuller @JonathanShaw 
Would anyone mind having a quick look ?

**Comment by danielbaker** [comment]
looks good :+1:

**Comment by MingtaoSun** [comment]
:+1:

**Comment by yetti** [comment]
:+1:

**Pull request merged**
