### PR TITLE
adding web address/URL for eDeposit publication.

### PR DESCRIPTION
**Pull request by shuangzhou**
This provides the web address/URL for eDeposit publication required for DDG-482.

### CODE REVIEW

**Comment by shuangzhou** [comment]
@sjacob @jrixon @scoen @terenceingram could you please review this update?  thanks.

**Comment by nlabuilder** [comment]
Build finished.

**Comment by jrixon** [comment]
@shuangzhou 

Hi Shuang,

I've tagged Chris in a comment in the jira:
http://ourweb.nla.gov.au/apps/jira/browse/DDG-482

So you two can co-ordinate on the name of the field.

Would it be possible to make the changes to EDepositNewMaterialJobsController before merging? Just because this on its own doesn't really do much.

-Jeremy
@xtfer

**Comment by shuangzhou** [comment]
@jrixon @sjacob thanks for liaising and providing the info, as this field should be invisible and non-editable in banjo, I'll close this request.

**Pull request closed without merging**
