### PR TITLE
Update version

### PR DESCRIPTION
**Pull request by shuangzhou**
Update to use latest DoSS version and maintain api compatibility for AmberQueryBase.

### CODE REVIEW

**Comment by shuangzhou** [comment]
@scoen @jrixon @m-r-c @ninhnguyen could you please review?  Thanks.

**Comment by nlabuilder** [comment]
SonarQube analysis reported 1 issue

1. MINOR [AmberQueryBase.java#L17](https://github.com/nla/amberdb/blob/4782daad686b871481182fa5b27d8bbd705a5c06/src/main/java/amberdb/graph/AmberQueryBase.java#L17): Define a constant instead of duplicating this literal "select * \n" 4 times. [rule](https://sonarqube.nla.gov.au/coding_rules#rule_key=squid%3AS1192)

**Comment by nlabuilder** [comment]
Build finished.

**Comment by m-r-c** [comment]
👍

**Pull request merged**
