### PR TITLE
Bs dscs 539 fa update

### PR DESCRIPTION
**Pull request by bsingh-nla**
@scoen I'm back with FINDING_AID copy role 1 to 10 :)

### CODE REVIEW

**Comment by MingtaoSun** [comment]
Looks like I should have made the gap 100 instead of 10 :smile:

**Comment by bsingh-nla** [comment]
@MingtaoSun  :wink: Probably that's not enough...if i add finding aid copy role 1 to 100

**Comment by AaronCMuller** [comment]
Why?

**Comment by bsingh-nla** [comment]
@AaronCMuller you mean why finding aid 1 to 10 again?

**Comment by AaronCMuller** [comment]
Yes.

**Comment by bsingh-nla** [comment]
Probably Kavinga can answer it better.

**Comment by JonathanShaw** [comment]
I'm probably just being slow here but what was the reason we aren't dealing with multiple Finding Aid copies? I thought AmberDb had been updated to allow this

**Comment by bsingh-nla** [comment]
Again, not sure. Kavinga is the right person to answer this.

**Pull request closed without merging**
