### PR TITLE
DSCS-2364 Update AmberEdgeQuery.java to use AmberDB v2 tables

### PR DESCRIPTION
**Pull request by jrixon**
@scoen @yetti @ninhnguyen @shuangzhou @weijunnla @m-r-c

### CODE REVIEW

**Comment by shuangzhou** [comment]
👍

**Comment by yetti** [comment]
Yay! No more temporary tables! 💯

**Comment by nlabuilder** [comment]
SonarQube analysis reported 3 issues

1. MINOR [AmberEdgeQuery.java#L12](https://github.com/nla/amberdb/blob/f4c26e4edda994191628647d56c759a190b629ec/src/main/java/amberdb/graph/AmberEdgeQuery.java#L12): Remove this unused import 'org.skife.jdbi.v2.Update'. [rule](https://sonarqube.nla.gov.au/coding_rules#rule_key=squid%3AUselessImportCheck)
1. MINOR [AmberEdgeQuery.java#L104](https://github.com/nla/amberdb/blob/f4c26e4edda994191628647d56c759a190b629ec/src/main/java/amberdb/graph/AmberEdgeQuery.java#L104): Define a constant instead of duplicating this literal "from flatedge \n" 3 times. [rule](https://sonarqube.nla.gov.au/coding_rules#rule_key=squid%3AS1192)
1. MINOR [AmberEdgeQuery.java#L105](https://github.com/nla/amberdb/blob/f4c26e4edda994191628647d56c759a190b629ec/src/main/java/amberdb/graph/AmberEdgeQuery.java#L105): Define a constant instead of duplicating this literal "left join acknowledge on flatedge.id = acknowledge.id \n" 3 times. [rule](https://sonarqube.nla.gov.au/coding_rules#rule_key=squid%3AS1192)

**Comment by nlabuilder** [comment]
Build finished.

**Pull request merged**
