### PR TITLE
ACJP-9 adds ability to revert changes to a specific work in an amber …

### PR DESCRIPTION
**Pull request by m-r-c**
…session (used by banjo jobs when aborting failed items)

@scoen @adityaburra @sjacob @ninhnguyen @yetti

### CODE REVIEW

**Comment by nlabuilder** [comment]
Build finished.

**Comment by nlabuilder** [comment]
Build finished.

**Comment by nlabuilder** [comment]
Build finished.

**Comment by adityaburra** [comment]
👍

**Pull request merged**
