### PR TITLE
Check if work is a valid sound work

### PR DESCRIPTION
**Pull request by yetti**
OK, let's try this again. @danielbaker @AaronCMuller

### CODE REVIEW

**Comment by danielbaker** [comment]
I like it!

**Comment by JonathanShaw** [comment]
I like this,  you can probably refactor a couple of things to use this if you're feeling like it. Off the top of my head spreadsheet upload, sound consignment utils and the work edit page all would be able to use this.

**Comment by yetti** [comment]
Yep, looking at sound consignment and spreadsheet upload atm since I'm already working on sound consignment.

**Comment by JonathanShaw** [comment]
thanks :)

**Pull request merged**
