### PR TITLE
adding mysql replace for dup entry work around.

### PR DESCRIPTION
**Pull request by shuangzhou**
This provides additional guarantee for not inserting dup entry in the persistence data.

### CODE REVIEW

**Comment by shuangzhou** [comment]
@scoen @jrixon could you please review?  Thanks.

**Comment by scoen** [comment]
I think that looks fair enough.
Note: will likely not work on h2

**Comment by jrixon** [comment]
@scoen we don't have the primary keys in the h2 db so we don't need to make the same change in the h2 dao

**Comment by jrixon** [comment]
@shuangzhou 
Looks good.

**Comment by shuangzhou** [comment]
Thanks both :-)

**Comment by scoen** [comment]
@jrixon @shuangzhou 
Yeah, it's a minor thing - not significant here. I'm just not certain h2 understands the `REPLACE` statement as valid sql.

**Pull request merged**
