### PR TITLE
Deleting all the EAD upload code. It is all moved into Banjo

### PR DESCRIPTION
**Pull request by danielbaker**
It was confusing having the EAD code living in amberdb, so its all been deleted and moved into Banjo.

@AaronCMuller @scoen

### CODE REVIEW

**Comment by danielbaker** [comment]
Whats the deal with the failing travis build? The test which is says is failing passes locally and I dont think I have touch anything in that area. Is there some way to debug?

**Comment by scoen** [comment]
Hi Daniel,

I�ll take a look. It does appear to be completely unrelated. Let you know what I find soon

**Comment by scoen** [comment]
@danielbaker 
Well, it's passing now so i'm going to merge. I couldn't discover why it failed the first time. Can't see the surefire test results.

**Comment by AaronCMuller** [comment]
Wow, that's a lot of lines!

**Pull request merged**
