### PR TITLE
ms2153: add a new copy role

### PR DESCRIPTION
**Pull request by MingtaoSun**
http://ourweb.nla.gov.au/apps/jira/browse/DSCS-2153
@JonathanShaw @shuangzhou @josephcurtis @yetti

### CODE REVIEW

**Comment by yetti** [comment]
looks fine

**Comment by shuangzhou** [comment]
@MingtaoSun don't forget to update unit test.

**Comment by MingtaoSun** [comment]
@shuangzhou , yep, fixed. My brain is still in holiday mood :disappointed:

**Comment by shuangzhou** [comment]
@MingtaoSun great, looks good to me.

**Pull request merged**
