### PR TITLE
DDG394 Add a new field 'Access agreement' to Banjo work records

### PR DESCRIPTION
**Pull request by weijunnla**
DDG-394 New work record field in Banjo
The task is to add a new field 'Access agreement' to Banjo work records, with four allowed values:
* Open access immediately
* Open access (embargoed)
* Basic access (as per Copyright Act)
* empty (some records may have no value so allow the value to be blank)

This is the first part of implementation. All other changes have dependency on this. 

The whole task includes:
1. amberdb database update (altering table and new lookup values)
2. Changes in amberdb 
3. Changes in dl-indexer-service
4. Changes in jelly-solr
5. Changes in banjo 

@scoen @jrixon @sjacob @yetti @shuangzhou  Could you please review (related review requests will be sent to you as well)?

### CODE REVIEW

**Comment by nlabuilder** [comment]
Build finished.

**Comment by scoen** [comment]
Could you make the version 2.0.1 rather than 2.1 ?
(my bad, i asked you to just increment the last number)

**Comment by weijunnla** [comment]
@scoen Sure

**Comment by nlabuilder** [comment]
SonarQube analysis reported 3 issues

1. MINOR [Work.java#L292](https://github.com/nla/amberdb/blob/edc61aca02d5f217973b2ceb82312b7443f318a8/src/main/java/amberdb/model/Work.java#L292): Document this public method. [rule](https://sonarqube.nla.gov.au/coding_rules#rule_key=squid%3AUndocumentedApi)
1. MINOR [Work.java#L295](https://github.com/nla/amberdb/blob/edc61aca02d5f217973b2ceb82312b7443f318a8/src/main/java/amberdb/model/Work.java#L295): Document this public method. [rule](https://sonarqube.nla.gov.au/coding_rules#rule_key=squid%3AUndocumentedApi)
1. MINOR [LookupsSchema.java#L1048](https://github.com/nla/amberdb/blob/edc61aca02d5f217973b2ceb82312b7443f318a8/src/main/java/amberdb/sql/LookupsSchema.java#L1048): Document this public method. [rule](https://sonarqube.nla.gov.au/coding_rules#rule_key=squid%3AUndocumentedApi)

**Comment by nlabuilder** [comment]
Build finished.

**Comment by nlabuilder** [comment]
Build finished.

**Pull request merged**
