### PR TITLE
ms464: add hasImageAccessCopy method

### PR DESCRIPTION
**Pull request by MingtaoSun**
@scoen @bsingh-nla add a new method
http://ourweb.nla.gov.au/apps/jira/browse/DSCS-464

### CODE REVIEW

**Comment by bsingh-nla** [comment]
All checks have failed :smile: 
@MingtaoSun what have you done, Ming

**Comment by bsingh-nla** [comment]
code looks good to me except CI check failure above.

**Comment by MingtaoSun** [comment]
@bsingh-nla , two tests failed. These two tests do fail occasionally. How to trigger the CI to run again?

**Comment by brycollins** [comment]
why would something fail 'occasionally' ?? sounds like theres more to the issue

**Comment by MingtaoSun** [comment]
I noticed this test TagTest#nodeTaggingTests has failed more than once before. Didn't pay much attention to which line fails though. @scoen , Hey Shaun, do you know much about this test?

**Comment by bsingh-nla** [comment]
all tests are passing locally for this branch, so got no idea why travis is not happy...may be its Tuesday :wink:

**Comment by scoen** [comment]
I've modified Daniel's abstract test class and changed the TagTest to use it to see if that fixes the problem.

**Pull request merged**
